### PR TITLE
Feature1

### PR DESCRIPTION
**Pull request by uwadonat**
### top_sellers web app development:

In this project I:
    - Built a single page application (SPA) with React and Redux.
    - Managed to retrieve data and store them in the Redux store.
    - filtered the data that I retrieved from the API using a Filter stateless component.
    - implemented a unique route within the SPA for each page.
    - deployed the web app and make it accessible online

**Hope to meet all requirements of this project** 

_Thank you for your time to review my project_

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi @uwadonat , 

Good job so far! Your application is almost complete, your README file is complete, good use of React/Redux and the consumption of the API works as expected🔥🔥

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [x] The link of your video on your README file is broken, please fix it, the video is a hard requirement, without it we can't approve your project.

- [x] You are not following the given design, remember that you need to use the exact color and fonts as well as the layout(which in this case you are right), even you can improve your app greatly if you add some images as the original design, remember that UI/UX is equally important than the code.

Original design:

imagen

imagen

Your design:

imagen

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uwadonat** [comment]
Thank you for good feedback. Changes requested was implemented.

**Review by mricanho — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @uwadonat 🔥 

Now your capstone project looks more professional, good work on all the changes, nothing more to add here👍🏽 

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uwadonat** [comment]
Thanks!

**Pull request merged**
